/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.25.3
 * source: proto_common.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export declare namespace common {
    class ProtoLocation extends pb_1.Message {
        one_of_decls: number[][];
        constructor(data?: any[] | {
            value?: Uint8Array;
        });
        get value(): Uint8Array;
        set value(value: Uint8Array);
        static fromObject(data: {
            value?: Uint8Array;
        }): ProtoLocation;
        toObject(): {
            value?: Uint8Array | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ProtoLocation;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ProtoLocation;
    }
    class ProtoHash extends pb_1.Message {
        one_of_decls: number[][];
        constructor(data?: any[] | {
            value?: Uint8Array;
        });
        get value(): Uint8Array;
        set value(value: Uint8Array);
        static fromObject(data: {
            value?: Uint8Array;
        }): ProtoHash;
        toObject(): {
            value?: Uint8Array | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ProtoHash;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ProtoHash;
    }
    class ProtoHashes extends pb_1.Message {
        one_of_decls: number[][];
        constructor(data?: any[] | {
            hashes?: ProtoHash[];
        });
        get hashes(): ProtoHash[];
        set hashes(value: ProtoHash[]);
        static fromObject(data: {
            hashes?: ReturnType<typeof ProtoHash.prototype.toObject>[];
        }): ProtoHashes;
        toObject(): {
            hashes?: {
                value?: Uint8Array | undefined;
            }[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ProtoHashes;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ProtoHashes;
    }
    class ProtoAddress extends pb_1.Message {
        one_of_decls: number[][];
        constructor(data?: any[] | {
            value?: Uint8Array;
        });
        get value(): Uint8Array;
        set value(value: Uint8Array);
        static fromObject(data: {
            value?: Uint8Array;
        }): ProtoAddress;
        toObject(): {
            value?: Uint8Array | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ProtoAddress;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ProtoAddress;
    }
}
//# sourceMappingURL=proto_common.d.ts.map