name: Manual Dev Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        required: true
        default: 'main'
jobs:
  call-common-workflow:
    uses: dominant-strategies/quai-cicd/.github/workflows/deploy-dev-common.yml@main
    with:
      needs_build: true
      install_command: "npm ci"
      build_command: "npm run build-clean && npm run test-unit && npm run test-integ-containers"
      cloud_deploy: false
      skip_deploy: true
      update_version: false
      needs_docker: false
      include_chart: false
      needs_docker_compose: true
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      BUILD_ARGS: ''
